### ISSUE TITLE
Demultiplexing samples using barcode sequences

### ISSUE THREAD

**Issue by husamia** [pierrepeterlongo/back_to_sequences#2]
How would you suggest using this tool to perform sample demultiplexing using known barcode sequences?

**Comment by pierrepeterlongo** [comment]
What is the size of the barcode sequences?

**Comment by husamia** [comment]
@pierrepeterlongo the barcode sequence is 10 bps. There is an adapter sequence that could make it longer.

**Comment by pierrepeterlongo** [comment]
Hello. 

I do not think "back to sequences" is designed for this task. Demultiplexing requires assigning each barcode (or pair of barcodes) to a piece of information (i.e. a sample). This is not a feature currently implemented in "back to sequences". 

What would be the advantages compared to tools specifically designed for this task such as frogs? 
https://frogs.toulouse.inra.fr/
