### ISSUE TITLE
Question reads/assembly

### ISSUE THREAD

**Issue by cmonat** [pierrepeterlongo/back_to_sequences#5]
Hello,

thanks for this promising tool you've developed.
Is the tool designed to work specifically on raw reads instead of assembly or if both entries are possible?
Thanks

Have a great day
C.

**Comment by pierrepeterlongo** [comment]
Hello, 

The tool is meant to find kmers from any sequence (reads, genomes, MAGs, contigs, ...) in any sequence. So these kmers can be found in raw reads, or genomes, transcriptomes, etc.

Best, 
Pierre
