### ISSUE TITLE
JOSS Review

### ISSUE THREAD

**Issue by amoeba** [pierrepeterlongo/back_to_sequences#8]
Ref my checklist: https://github.com/openjournals/joss-reviews/issues/7066#issuecomment-2297831057

Hi @pierrepeterlongo, I've had a chance to sit down with https://github.com/pierrepeterlongo/back_to_sequences/ and things look mostly in order. This looks like a generally useful piece of software and I appreciate the effort you've put into the source code, documentation, and the paper. 

Below are my review comments, all of which should be addressed before acceptance.

## Functionality

_Needs changes_

- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)
  - I wasn't able to run the benchmarks as-is. It looks like the data generation script and the benchmarking script don't agree about what size reads to benchmark. I edited the file manually to make the benchmarks run and was able to confirm the software performs about as fast as you say. Please fix the benchmark scripts so they run out of the box.

## Documentation

_Needs changes_

- Because the JOSS submission is an archive of the source code, it's important that the documentation for the software is contained within that archive. While [the documentation
](https://b2s-doc.readthedocs.io/) is good, I noticed that it lives in a repo separate from the source code being submitted here. Therefore, I suggest the documentation in https://github.com/pierrepeterlongo/b2s_doc be moved into https://github.com/pierrepeterlongo/back_to_sequences/. Let me know if this isn't possible for some reason and we can probably work something out.
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support
  - This is missing. Please add it in the README and also in the docs website.
- Overall the main README is a bit sparse. It would be good if it had sections for Installation, Usage (it does now), Benchmarks, and Community Guidelines. It could still link to the full documentation website.

## Software paper

_Needs changes_

The paper was generally well-written but contained too much information for JOSS. See https://joss.readthedocs.io/en/latest/paper.html#what-should-my-paper-contain for the allowed sections. [I've filed a PR](https://github.com/pierrepeterlongo/back_to_sequences/pull/7) to remove the sections which also includes a variety of other fix-ups. The content I removed is very interesting and I think it would be good to retain it in some form. Maybe on the documentation website?

Please let me know if you have any questions. Thanks for your time.

**Comment by pierrepeterlongo** [comment]
Hello @amoeba 

> I wasn't able to run the benchmarks as-is

This is now fixed. And a new cleaning script was added

**Comment by pierrepeterlongo** [comment]
> I suggest the documentation in https://github.com/pierrepeterlongo/b2s_doc be moved into https://github.com/pierrepeterlongo/back_to_sequences/.

We have made the decision to separate the documentation from the github repo because the last item of this [recommendation](https://github.com/openjournals/joss-reviews/issues/6872#issuecomment-2205642997). It seems to me that this separation is required, even if I'm not 100% sure of this claim.

Anyway we added specific pieces of information in the README.

**Comment by pierrepeterlongo** [comment]
> Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

We now clearly link the [CONTRIBUTING](https://github.com/pierrepeterlongo/back_to_sequences/blob/main/CONTRIBUTING.md) file in the README.

**Comment by pierrepeterlongo** [comment]
> Overall the main README is a bit sparse. It would be good if it had sections for Installation, Usage (it does now), Benchmarks, and Community Guidelines. It could still link to the full documentation website.

As mentioned we updated the README. We can further change the balance between this README and the external documentation if required.

**Comment by pierrepeterlongo** [comment]
> remove the sections which also includes a variety of other fix-ups.

Thank you again for this important work.
We have applied the pull request and adjusted the rest of the manuscript. The parts you removed have been transferred to the documentation.

**Comment by amoeba** [comment]
Thanks @pierrepeterlongo.
